import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import ThemeCom from "../components/ThemeCom";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({
  variable: "--font-inter", 
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" suppressHydrationWarning>
      <body >
        <ThemeCom>
        <Header/>
        {children}
        </ThemeCom>
      </body>
    </html>
    </ClerkProvider>
  );
}
